export const COUNTRY_QUESTION = "COUNTRY_QUESTION";
export type COUNTRY_QUESTION = typeof COUNTRY_QUESTION;

export const CAPITAL_QUESTION = "CAPITAL_QUESTION";
export type CAPITAL_QUESTION = typeof CAPITAL_QUESTION;

export type QUESTION_TYPE = COUNTRY_QUESTION | CAPITAL_QUESTION;
